# Generated by Django 2.2.2 on 2019-07-29 15:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geo',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
