version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: signmob_production_django
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    ports:
      - "127.0.0.1:8050:5000"
    env_file:
      - ./.env
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: signmob_production_postgres
    restart: unless-stopped
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.env

  redis:
    image: redis:5.0
    restart: unless-stopped

  celeryworker:
    <<: *django
    image: signmob_production_celeryworker
    restart: unless-stopped
    command: /start-celeryworker
    ports: []

  celerybeat:
    <<: *django
    image: signmob_production_celerybeat
    restart: unless-stopped
    command: /start-celerybeat
    ports: []

  flower:
    <<: *django
    image: signmob_production_flower
    restart: unless-stopped
    ports:
      - "127.0.0.1:5555:5555"
    command: /start-flower
