# Generated by Django 2.2.2 on 2019-06-23 13:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0011_event_calendar_not_null"),
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionevent",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="collectionevent",
            name="event_occurence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schedule.Occurrence",
            ),
        ),
        migrations.AddField(
            model_name="collectionevent",
            name="geo",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="collectionevent",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="collectioneventmember",
            name="end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collectioneventmember",
            name="start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collectiongroup",
            name="calendar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schedule.Calendar",
            ),
        ),
        migrations.AddField(
            model_name="collectiongroup",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="collectionlocation",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="collectionlocation",
            name="geo",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="collectionlocation",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="collectionlocation",
            name="start",
            field=models.DateField(null=True),
        ),
    ]
