# Generated by Django 2.2.2 on 2019-07-07 17:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("collection", "0003_auto_20190623_1528")]

    operations = [
        migrations.AddField(
            model_name="collectiongroup",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="collectiongroup",
            name="geo",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="collectiongroupmember",
            name="joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="collectionlocation",
            name="accumulation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="collectionlocation",
            name="address",
            field=models.TextField(blank=True),
        ),
    ]
