# Generated by Django 2.2.2 on 2019-07-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_event_calendar_not_null'),
        ('collection', '0005_auto_20190709_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionlocation',
            name='calendar',
        ),
        migrations.AddField(
            model_name='collectiongroup',
            name='channel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collectionlocation',
            name='events',
            field=models.ManyToManyField(to='schedule.Event'),
        ),
        migrations.AddField(
            model_name='collectionlocation',
            name='needs_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectionlocation',
            name='report',
            field=models.TextField(blank=True),
        ),
    ]
