# Generated by Django 2.2.2 on 2019-07-11 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0006_auto_20190710_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectioneventmember',
            options={'ordering': ('start', '-end'), 'verbose_name': 'Sammelterminteilnehmer/in', 'verbose_name_plural': 'Sammelterminteilnehmende'},
        ),
        migrations.AddField(
            model_name='collectioneventmember',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='event_occurence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Occurrence'),
        ),
        migrations.AlterField(
            model_name='collectionlocation',
            name='events',
            field=models.ManyToManyField(blank=True, to='schedule.Event'),
        ),
        migrations.AlterUniqueTogether(
            name='collectiongroupmember',
            unique_together={('group', 'user')},
        ),
    ]
