# Generated by Django 2.2.2 on 2019-07-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20190711_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionlocation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
