# Generated by Django 2.2.2 on 2019-07-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_collectiongroupmember_responsible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectiongroup',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='collectiongroupmember',
            options={'verbose_name': 'Teammitglied', 'verbose_name_plural': 'Teammitglieder'},
        ),
    ]
