# Generated by Django 2.2.2 on 2019-08-12 10:38

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_auto_20190729_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionevent',
            options={'ordering': ('-event_occurence__start',), 'verbose_name': 'collection event', 'verbose_name_plural': 'collection events'},
        ),
        migrations.AlterModelOptions(
            name='collectioneventmember',
            options={'ordering': ('start', '-end'), 'verbose_name': 'collection event member', 'verbose_name_plural': 'collection event member'},
        ),
        migrations.AlterModelOptions(
            name='collectiongroup',
            options={'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
        migrations.AlterModelOptions(
            name='collectiongroupmember',
            options={'verbose_name': 'team member', 'verbose_name_plural': 'team members'},
        ),
        migrations.AlterModelOptions(
            name='collectionlocation',
            options={'verbose_name': 'collection place', 'verbose_name_plural': 'collection places'},
        ),
        migrations.AlterModelOptions(
            name='collectionresult',
            options={'verbose_name': 'collection result', 'verbose_name_plural': 'collection results'},
        ),
        migrations.AddField(
            model_name='collectionlocation',
            name='send_material',
            field=models.BooleanField(default=False, verbose_name='send material'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='event_occurence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Occurrence', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='geo',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='place'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.CollectionGroup', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='members',
            field=models.ManyToManyField(through='collection.CollectionEventMember', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='collectioneventmember',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='collectioneventmember',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.CollectionEvent', verbose_name='collection event'),
        ),
        migrations.AlterField(
            model_name='collectioneventmember',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='collectioneventmember',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='collectioneventmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='collectiongroup',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Calendar', verbose_name='calendar'),
        ),
        migrations.AlterField(
            model_name='collectiongroup',
            name='channel',
            field=models.CharField(blank=True, max_length=255, verbose_name='channel'),
        ),
        migrations.AlterField(
            model_name='collectiongroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='collectiongroup',
            name='geo',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='place'),
        ),
        migrations.AlterField(
            model_name='collectiongroup',
            name='members',
            field=models.ManyToManyField(through='collection.CollectionGroupMember', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
        migrations.AlterField(
            model_name='collectiongroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='collectiongroupmember',
            name='joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='joined'),
        ),
        migrations.AlterField(
            model_name='collectiongroupmember',
            name='responsible',
            field=models.BooleanField(default=False, verbose_name='responsible'),
        ),
        migrations.AlterField(
            model_name='collectiongroupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='collectionlocation',
            name='accumulation',
            field=models.BooleanField(default=False, verbose_name='accumulation'),
        ),
        migrations.AlterField(
            model_name='collectionlocation',
            name='address',
            field=models.TextField(blank=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='collectionlocation',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='collectionlocation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='collectionlocation',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='collectionlocation',
            name='events',
            field=models.ManyToManyField(blank=True, to='schedule.Event', verbose_name='opening hours'),
        ),
        migrations.AlterField(
            model_name='collectionlocation',
            name='geo',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='place'),
        ),
        migrations.AlterField(
            model_name='collectionlocation',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='collectionlocation',
            name='needs_check',
            field=models.BooleanField(default=False, verbose_name='needs check'),
        ),
        migrations.AlterField(
            model_name='collectionlocation',
            name='report',
            field=models.TextField(blank=True, verbose_name='report'),
        ),
        migrations.AlterField(
            model_name='collectionlocation',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='collectionlocation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='collectionresult',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='collectionresult',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='collectionresult',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='collectionresult',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.CollectionEvent', verbose_name='collection event'),
        ),
        migrations.AlterField(
            model_name='collectionresult',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.CollectionGroup', verbose_name='team'),
        ),
        migrations.AlterField(
            model_name='collectionresult',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.CollectionLocation', verbose_name='collection location'),
        ),
        migrations.AlterField(
            model_name='collectionresult',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='collectionresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
